name: Security check - Bandit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install bandit
      run: |
        sudo snap install bandit
    - name: Use bandit
      run: |
        bandit -r .
